### ISSUE TITLE
Running SpatialPPI wth a protein structure

### ISSUE THREAD

**Issue by KoussaiB** [ohuelab/SpatialPPI#1]
Hello, 

Thank you for this useful tool :)

Wanted to ask if it is possible to modify the scripts in way that we could directly input two PDB files (of the interacting proteins) to the pre-processing part in order to evaluate the interaction? 

Thanks in advance!

**Comment by perseids2032** [comment]
I'm afraid not. It needs the structure information between the two potential interactors predicted from AF-Multimer.
